name = "ITensorNetworksQiskit"
uuid = "9bbb9987-8b45-47af-9bc5-5060d48a7bd4"
authors = ["Lewis Anderson", "Kate Marshall", "Ben Jaderberg"]
version = "1.0.0-DEV"

[deps]
DataGraphs = "b5a273c3-7e6c-41f6-98bd-8d7f1525a36a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"
OMEinsumContractionOrders = "6f22d1fd-8eed-4bb7-9776-e7d684900715"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TensorNetworkQuantumSimulator = "4de3b72a-362e-43dd-83ff-3f381eda9f9c"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
# Counters = "5a653867-b65e-5b16-a095-b1e26d522bbf"
[compat]
Dictionaries = "0.4.2"
Glob = "1.3.1"
Graphs = "1.11.0"
# ITensorNetworks = "0.13.3" # I had to comment this line. Otherwise I was getting errors in the installation.
ITensors = "0.9.1"
NamedGraphs = "0.7"
julia = "1.11"
PythonCall = "=0.9.30"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
